In [ ]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (8.1.7)
Collecting joblib (from nltk)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.5 MB 1.9 MB/s eta 0:00:01
   - -------------------------------------- 0.0/1.5 MB 1.9 MB/s eta 0:00:01
   -- ------------------------------------- 0.1/1.5 MB 751.6 kB/s eta 0:00:02
   -- ------------------------------------- 0.1/1.5 MB 751.6 kB/s eta 0:00:02
   -- ------------------------------------- 0.1/1.5 MB 751.6 kB/s eta 0:00:02
   ----- ---------------------------------- 0.2/1.5 MB 808.4 kB/s eta 0:00:02
   ------ --------------------------------- 0.2/1.5 MB 722.1 kB/s eta 0:00:02
   ------ --------------------------------- 0.2/1.5 MB 722.1 kB/s eta 0:00:02
   ------- -------------------------------- 0.3/1.5 MB 630.9 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.5 MB 972.0 kB/s eta 0:00:02
   -------------- ------------------------- 0.5/1.5 MB 1.0 MB/s eta 0:00:01
   ------------------ --------------------- 0.7/1.5 MB 1.2 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.5 MB 1.3 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.5 MB 1.3 MB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.5 MB 1.3 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------- ----------- 1.1/1.5 MB 1.4 MB/s eta 0:00:01
   -------------------------------- ------- 1.2/1.5 MB 1.4 MB/s eta 0:00:01
   -------------------------------- ------- 1.2/1.5 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 1.4 MB/s eta 0:00:00
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
   ---------------------------------------- 0.0/307.7 kB ? eta -:--:--
   ------------------------------ --------- 235.5/307.7 kB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 266.2/307.7 kB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 266.2/307.7 kB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 307.7/307.7 kB 1.9 MB/s eta 0:00:00
Installing collected packages: joblib, nltk
Successfully installed joblib-1.5.1 nltk-3.9.1

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\hkuma\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (2.1.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hkuma\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\hkuma\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
netflix_df= pd.read_csv('netflixData.csv')
netflix_df.head()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,NaN,Reality TV,NaN,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,"September 8, 2020"
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,"July 1, 2020"
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,NaN,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",NaN,Canada,2020.0,TV-14,90 min,5.1/10,Movie,"February 5, 2020"

In [5]:
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5967 entries, 0 to 5966
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Show Id             5967 non-null   object
 1   Title               5967 non-null   object
 2   Description         5967 non-null   object
 3   Director            3903 non-null   object
 4   Genres              5967 non-null   object
 5   Cast                5437 non-null   object
 6   Production Country  5408 non-null   object
 7   Release Date        5964 non-null   float64
 8   Rating              5963 non-null   object
 9   Duration            5964 non-null   object
 10  Imdb Score          5359 non-null   object
 11  Content Type        5967 non-null   object
 12  Date Added          4632 non-null   object
dtypes: float64(1), object(12)
memory usage: 606.2+ KB

In [6]:
netflix_df.isnull()

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,False,False,False,True,False,True,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,False,False,False,False,False,False,False,False,False,False,False,False,False
5963,False,False,False,True,False,False,True,False,False,False,True,False,True
5964,False,False,False,True,False,False,True,False,False,False,True,False,True
5965,False,False,False,False,False,False,False,False,False,False,False,False,False
5966,False,False,False,False,False,False,True,False,False,False,False,False,False

In [7]:
netflix_df.isnull().sum()

Show Id                  0
Title                    0
Description              0
Director              2064
Genres                   0
Cast                   530
Production Country     559
Release Date             3
Rating                   4
Duration                 3
Imdb Score             608
Content Type             0
Date Added            1335
dtype: int64

In [9]:
required_nf_df=netflix_df[['Title','Description','Content Type','Genres']]
required_nf_df.head()

,Title,Description,Content Type,Genres
0,(Un)Well,This docuseries takes a deep dive into the luc...,TV Show,Reality TV
1,#Alive,"As a grisly virus rampages a city, a lone man ...",Movie,"Horror Movies, International Movies, Thrillers"
2,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...",Movie,"Documentaries, International Movies"
3,#blackAF,Kenya Barris and his family navigate relations...,TV Show,TV Comedies
4,#cats_the_mewvie,This pawesome documentary explores how our fel...,Movie,"Documentaries, International Movies"

In [10]:
#Drop the rows which has null values
required_nf_df.dropna()

,Title,Description,Content Type,Genres
0,(Un)Well,This docuseries takes a deep dive into the luc...,TV Show,Reality TV
1,#Alive,"As a grisly virus rampages a city, a lone man ...",Movie,"Horror Movies, International Movies, Thrillers"
2,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...",Movie,"Documentaries, International Movies"
3,#blackAF,Kenya Barris and his family navigate relations...,TV Show,TV Comedies
4,#cats_the_mewvie,This pawesome documentary explores how our fel...,Movie,"Documentaries, International Movies"
...,...,...,...,...
5962,الف مبروك,"On his wedding day, an arrogant, greedy accoun...",Movie,"Comedies, Dramas, International Movies"
5963,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,TV Show,"International TV Shows, TV Dramas"
5964,海的儿子,"Two brothers start a new life in Singapore, wh...",TV Show,"International TV Shows, TV Dramas"
5965,반드시 잡는다,After people in his town start turning up dead...,Movie,"Dramas, International Movies, Thrillers"
5966,최강전사 미니특공대 : 영웅의 탄생,"Miniforce, a special task force of elite range...",Movie,Children & Family Movies

In [11]:
required_nf_df.count()

Title           5967
Description     5967
Content Type    5967
Genres          5967
dtype: int64

In [12]:
#Clean the data
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hkuma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
stemmer=nltk.SnowballStemmer('english')
from nltk.corpus import stopwords
import string
stopword=set(stopwords.words('english'))

In [ ]:
#Clean the data
import re
def clean(text):
    text = str(text).lower() # Convert to string and lowercase
    text = re.sub('\[.*?\]','', text) # Remove square brackets and their contents 
    text = re.sub('https?://\S+|www\,\S++', '', text)  # Remove URLs
    text = re.sub('<.*?>+', '', text)# Remove HTML tags
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)# Remove punctuation
    text = re.sub('\n', '', text)# Remove new line characters
    text = re.sub('\w*\d\w*', '', text)# Remove words containing numbers
    text = [word for word in text.split(' ') if word not in stopword]# Remove stopwords
    text = ' '.join(text)# Join words back into a single string
    text = [stemmer.stem(word) for word in text.split(' ')]# Stem the words
    text = ' '.join(text)# Join stemmed words back into a single string
    return text

In [17]:
required_nf_df["Title"] = required_nf_df["Title"].apply(clean)
required_nf_df.head()

C:\Users\hkuma\AppData\Local\Temp\ipykernel_18108\2346077340.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  required_nf_df["Title"] = required_nf_df["Title"].apply(clean)

,Title,Description,Content Type,Genres
0,unwel,This docuseries takes a deep dive into the luc...,TV Show,Reality TV
1,aliv,"As a grisly virus rampages a city, a lone man ...",Movie,"Horror Movies, International Movies, Thrillers"
2,annefrank parallel stori,"Through her diary, Anne Frank's story is retol...",Movie,"Documentaries, International Movies"
3,blackaf,Kenya Barris and his family navigate relations...,TV Show,TV Comedies
4,catsthemewvi,This pawesome documentary explores how our fel...,Movie,"Documentaries, International Movies"

In [18]:
required_nf_df.Title.sample(10)

4485                 super monster monster pet
4256                          silvana sin lana
2397                       joaquín rey una más
4778                                      dirt
1093                              cook cannabi
374                  ani dr kashinath ghanekar
2675    lego marvel super hero aveng reassembl
820                                     broken
268                       ali  ratu ratu queen
5042                              memori water
Name: Title, dtype: object

In [19]:
genreList = required_nf_df['Genres'].tolist()
tfidf=text.TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(genreList)
similarity= cosine_similarity(tfidf_matrix)

In [20]:
indices=pd.Series(required_nf_df.index, index=required_nf_df['Title']).drop_duplicates()

In [25]:
def netflix_recommendation(title, similarity=similarity):
    index = indices[title]
    similarity_scores = list(enumerate(similarity[index]))
    similarity_scores =similarity_scores[0:10] 
    movieindices = [i[0] for i in similarity_scores]
    return required_nf_df['Title'].iloc[movieindices]

In [26]:
netflix_recommendation('fitoor')

0                        unwel
1                         aliv
2    annefrank  parallel stori
3                      blackaf
4                 catsthemewvi
5               friendbutmarri
6              friendbutmarri
7                  realityhigh
8
9                        selfi
Name: Title, dtype: object